ALTER TABLE `categories` CHANGE `createDate` `created` DATETIME NOT NULL;
ALTER TABLE `categories` CHANGE `lastUpdate` `updated` DATETIME NOT NULL;
ALTER TABLE `categories` CHANGE `lastVideoAddDate` `lastVideoAdded` DATETIME NOT NULL;
ALTER TABLE `categories` CHANGE `deleted` `isDeleted` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `categories` CHANGE `deleteDate` `deleted` DATETIME NOT NULL;
ALTER TABLE `categories` CHANGE `deleteUserId` `deletedById` INT(11) NOT NULL;
ALTER TABLE `categories` CHANGE `createUserId` `createdById` INT(11) NOT NULL;
ALTER TABLE `categories` CHANGE `createUserIP` `createdByIP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `categories` ADD `deletedByIP` VARCHAR(20) NOT NULL AFTER `deletedById`;
ALTER TABLE `categories` CHANGE `isDeleted` `isDeleted` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `comments` CHANGE `confirmed` `isConfirmed` BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE `comments` CHANGE `confirmUserId` `confirmedById` INT(11) NOT NULL;
ALTER TABLE `comments` CHANGE `confirmUserIP` `confirmedByIP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `comments` CHANGE `commentLastUpdate` `updated` DATETIME NOT NULL;
ALTER TABLE `comments` CHANGE `commentDate` `created` DATETIME NOT NULL;
ALTER TABLE `comments` CHANGE `lastUpdateUserId` `updatedById` INT(11) NOT NULL;
ALTER TABLE `comments` CHANGE `lastUpdateUserIP` `updatedByIP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `folders` CHANGE `folderName` `name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `folders` CHANGE `createDate` `created` DATETIME NOT NULL;
ALTER TABLE `folders` CHANGE `createUserId` `createdById` INT(11) NOT NULL;
ALTER TABLE `folders` CHANGE `createUserIP` `createdByIP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `folders` CHANGE `lastUpdateUserId` `updatedById` INT(11) NOT NULL;
ALTER TABLE `folders` CHANGE `lastUpdate` `updated` DATETIME NOT NULL;
ALTER TABLE `folders` ADD `updatedByIP` VARCHAR(20) NOT NULL AFTER `updatedById`;
ALTER TABLE `folders` CHANGE `lastVideoAddUserId` `lastVideoAddedById` INT(11) NOT NULL;
ALTER TABLE `folders` CHANGE `lastVideoAddDate` `lastVideoAdded` DATETIME NOT NULL;
ALTER TABLE `folders` CHANGE `deleted` `isDeleted` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `folders` CHANGE `deleteUserId` `deletedById` INT(11) NOT NULL;
ALTER TABLE `folders` CHANGE `deleteUserIP` `deletedByIP` INT(11) NOT NULL;
ALTER TABLE `folders` CHANGE `deleteDate` `deleted` DATETIME NOT NULL;
ALTER TABLE `messages` CHANGE `messageDate` `created` DATETIME NOT NULL;
ALTER TABLE `searches` CHANGE `searchDate` `created` DATETIME NOT NULL;
ALTER TABLE `users` CHANGE `name` `firstName` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `surname` `lastName` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `gender` `gender` ENUM('Male', 'Female') NOT NULL;
ALTER TABLE `users` CHANGE `registerDate` `registered` DATETIME NOT NULL;
ALTER TABLE `users` CHANGE `registerIP` `registeredByIP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `lastLoginDate` `lastLoggedIn` DATETIME NOT NULL;
ALTER TABLE `users` CHANGE `phone` `phoneNumber` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `deleted` `isDeleted` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `users` CHANGE `deleteDate` `deleted` DATETIME NOT NULL;
ALTER TABLE `users` CHANGE `deleteUserId` `deletedById` INT(11) NOT NULL;
ALTER TABLE `videos` CHANGE `addUserId` `addedById` INT(11) NOT NULL;
ALTER TABLE `videos` CHANGE `addUserIP` `addedByIP` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `videos` CHANGE `lastUpdateUserId` `updatedById` INT(11) NOT NULL;
ALTER TABLE `videos` CHANGE `deleted` `isDeleted` BOOLEAN NULL DEFAULT FALSE;
ALTER TABLE `videos` CHANGE `deleteDate` `deleted` DATETIME NOT NULL;
ALTER TABLE `videos` CHANGE `deleteUserId` `deletedById` INT(11) NOT NULL;

ALTER TABLE `questions` ADD `value` SMALLINT NOT NULL ;
ALTER TABLE `questions` ADD `bitValue` SMALLINT NOT NULL AFTER `id`;
ALTER TABLE `questions` ADD PRIMARY KEY(`id`);
UPDATE `youtube`.`questions` SET `bitValue` = '1' WHERE `questions`.`id` = 1;
UPDATE `youtube`.`questions` SET `bitValue` = '2' WHERE `questions`.`id` = 2;
UPDATE `youtube`.`questions` SET `bitValue` = '4' WHERE `questions`.`id` = 3;
UPDATE `youtube`.`questions` SET `bitValue` = '8' WHERE `questions`.`id` = 4;
ALTER TABLE `videos` CHANGE `questionBit` `questions` SMALLINT NOT NULL;
