ALTER TABLE `videoviews` CHANGE `actionDate` `actionDate` DATETIME NULL DEFAULT NULL;

ALTER TABLE `categories` DROP FOREIGN KEY `categories_ibfk_1`; ALTER TABLE `categories` ADD CONSTRAINT `categories_ibfk_1` FOREIGN KEY (`deletedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `categories` DROP FOREIGN KEY `categories_ibfk_2`; ALTER TABLE `categories` ADD CONSTRAINT `categories_ibfk_2` FOREIGN KEY (`createdById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `categories` DROP FOREIGN KEY `categories_ibfk_3`; ALTER TABLE `categories` ADD CONSTRAINT `categories_ibfk_3` FOREIGN KEY (`catGroupId`) REFERENCES `youtube`.`catgroups`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `comments` DROP FOREIGN KEY `comments_ibfk_1`; ALTER TABLE `comments` ADD CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`confirmedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `comments` DROP FOREIGN KEY `comments_ibfk_2`; ALTER TABLE `comments` ADD CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`createdById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `comments` DROP FOREIGN KEY `comments_ibfk_3`; ALTER TABLE `comments` ADD CONSTRAINT `comments_ibfk_3` FOREIGN KEY (`updatedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `folders` DROP FOREIGN KEY `folders_ibfk_1`; ALTER TABLE `folders` ADD CONSTRAINT `folders_ibfk_1` FOREIGN KEY (`createdById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `folders` DROP FOREIGN KEY `folders_ibfk_2`; ALTER TABLE `folders` ADD CONSTRAINT `folders_ibfk_2` FOREIGN KEY (`updatedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `folders` DROP FOREIGN KEY `folders_ibfk_3`; ALTER TABLE `folders` ADD CONSTRAINT `folders_ibfk_3` FOREIGN KEY (`lastVideoAddedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `folders` DROP FOREIGN KEY `folders_ibfk_4`; ALTER TABLE `folders` ADD CONSTRAINT `folders_ibfk_4` FOREIGN KEY (`deletedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `messages` DROP FOREIGN KEY `messages_ibfk_1`; ALTER TABLE `messages` ADD CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`createdById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `profileviews` DROP FOREIGN KEY `profileviews_ibfk_1`; ALTER TABLE `profileviews` ADD CONSTRAINT `profileviews_ibfk_1` FOREIGN KEY (`viewerId`) REFERENCES `youtube`.`users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `profileviews` DROP FOREIGN KEY `profileviews_ibfk_2`; ALTER TABLE `profileviews` ADD CONSTRAINT `profileviews_ibfk_2` FOREIGN KEY (`viewedId`) REFERENCES `youtube`.`users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `roleaccess` DROP FOREIGN KEY `roleaccess_ibfk_1`; ALTER TABLE `roleaccess` ADD CONSTRAINT `roleaccess_ibfk_1` FOREIGN KEY (`roleId`) REFERENCES `youtube`.`roles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `roleaccess` DROP FOREIGN KEY `roleaccess_ibfk_2`; ALTER TABLE `roleaccess` ADD CONSTRAINT `roleaccess_ibfk_2` FOREIGN KEY (`accessTypeId`) REFERENCES `youtube`.`accesstypes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `searches` DROP FOREIGN KEY `searches_ibfk_1`; ALTER TABLE `searches` ADD CONSTRAINT `searches_ibfk_1` FOREIGN KEY (`createdById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `users` DROP FOREIGN KEY `users_ibfk_2`; ALTER TABLE `users` ADD CONSTRAINT `users_ibfk_2` FOREIGN KEY (`languageId`) REFERENCES `youtube`.`languages`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `users` DROP FOREIGN KEY `users_ibfk_1`; ALTER TABLE `users` ADD CONSTRAINT `users_ibfk_1` FOREIGN KEY (`deletedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `videocats` DROP FOREIGN KEY `videocats_ibfk_1`; ALTER TABLE `videocats` ADD CONSTRAINT `videocats_ibfk_1` FOREIGN KEY (`videoId`) REFERENCES `youtube`.`videos`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `videocats` DROP FOREIGN KEY `videocats_ibfk_2`; ALTER TABLE `videocats` ADD CONSTRAINT `videocats_ibfk_2` FOREIGN KEY (`categoryId`) REFERENCES `youtube`.`categories`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `videos` DROP FOREIGN KEY `videos_ibfk_5`; ALTER TABLE `videos` ADD CONSTRAINT `videos_ibfk_5` FOREIGN KEY (`languageId`) REFERENCES `youtube`.`languages`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `videos` DROP FOREIGN KEY `videos_ibfk_2`; ALTER TABLE `videos` ADD CONSTRAINT `videos_ibfk_2` FOREIGN KEY (`addedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `videos` DROP FOREIGN KEY `videos_ibfk_3`; ALTER TABLE `videos` ADD CONSTRAINT `videos_ibfk_3` FOREIGN KEY (`updatedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE `videos` DROP FOREIGN KEY `videos_ibfk_4`; ALTER TABLE `videos` ADD CONSTRAINT `videos_ibfk_4` FOREIGN KEY (`deletedById`) REFERENCES `youtube`.`users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `videotags` DROP FOREIGN KEY `videotags_ibfk_1`; ALTER TABLE `videotags` ADD CONSTRAINT `videotags_ibfk_1` FOREIGN KEY (`tagId`) REFERENCES `youtube`.`tags`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `videotags` DROP FOREIGN KEY `videotags_ibfk_2`; ALTER TABLE `videotags` ADD CONSTRAINT `videotags_ibfk_2` FOREIGN KEY (`videoId`) REFERENCES `youtube`.`videos`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `videoviews` DROP FOREIGN KEY `videoviews_ibfk_1`; ALTER TABLE `videoviews` ADD CONSTRAINT `videoviews_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `youtube`.`users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `videoviews` DROP FOREIGN KEY `videoviews_ibfk_2`; ALTER TABLE `videoviews` ADD CONSTRAINT `videoviews_ibfk_2` FOREIGN KEY (`videoId`) REFERENCES `youtube`.`videos`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

